[package]
name = "game_frame"
version = "0.1.0"
authors = ["roger <rocurley@gmail.com>"]

[dependencies]
graph = { path = "../graph" }
types = { path = "../types" }
portal_graph= { path = "../portal_graph" }
