[package]

name = "game_state"
version = "0.1.0"
authors = ["Roger Curley <rocurley@gmail.com>"]

[dependencies]
tree = { path = "../tree" }
types = { path = "../types" }
conrod = "0.56.0"
glium = "0.18"
rand = "0.4.1"
ggez = "0.4.0-rc.2"
nalgebra = "0.13.1"
