[package]

name = "game_state"
version = "0.1.0"
authors = ["Roger Curley <rocurley@gmail.com>"]

[dependencies]
tree = { path = "../tree" }
types = { path = "../types" }
render = { path = "../render" }
rand = "0.4.1"
ggez = { path = "../../ggez" }
nalgebra = "0.13.1"
proptest = "0.4.0"
